baseurl: ''
exclude: ['README.md', node_modules]
permalink: pretty
title: '180 Degrees Consulting - University of Toronto'

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  teamleads:
    output: true
    permalink: /teamleads/:path/
  clients:
    output: true
    permalink: /clients/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables

theme: jekyll-theme-cayman